### ISSUE TITLE
com.urbanairship.android:urbanairship-fcm:16.8.1 notification permission bug

### ISSUE THREAD

**Issue by wezley98** [urbanairship/android-library#222] opened 2023-02-13 14:43 UTC
# Preliminary Info

### What Airship dependencies are you using?
com.urbanairship.android:urbanairship-fcm:16.8.1

# Report

### What unexpected behavior are you seeing?
Between 16.8.1 and 16.8.0 there seems to be a regression in the Android 13 notification permission behaviour.

16.8.1
--------
1. Disable notifications at OS level
2. Every time the app is open it asks to re-enable permissions. <---- bug?

16.8.0
-------
1. Disable notifications at OS level
2. Open the app, don't see notification permission.

### What is the expected behavior?
The behaviour seen in 16.8.0 is desired.

**Comment by rlepinski** [comment] 2023-02-13 16:49
@wezley98 I see where I went wrong. Ill try to have a patch release by tomorrow. 16.8.1 just moved the prompt to after onAirshipReady, so if you are not needing to modify push enabled flags or how it prompts before that callback, 16.8.0 is a fine version to stay on.

**Comment by rlepinski** [comment] 2023-02-13 17:24
I have a fix in review, the change is small but going to have our QA team regression test it since I clearly missed a test path

**Comment by rlepinski** [comment] 2023-03-02 17:19
Fixed in 16.9

**Closed by rlepinski** 2023-03-02 17:19 UTC
