### ISSUE TITLE
java.lang.RuntimeException Parcel android.os.Parcel@4e8f052c: Unmarshalling unknown type code 

### ISSUE THREAD

**Issue by prometheus-xiao** [urbanairship/android-library#3] opened 2016-11-03 09:37 UTC
Hi 
We got an crash issue on Fabric for our app, looks like this is Airship library issue. can you please help to check why it happened?
It is caught by Fabric, we can't reproduce it.

We use the version below.
'com.urbanairship.android:urbanairship-sdk:7.3.0'

Because the "minSdkVersion" of our app is 15, so we can't update Airship library to latest version(8.0.2) which "minSdkVersion" is 16. so we can't make is this issue still reproduced on the latest version.

the attachment 
[airship_crash.txt](https://github.com/urbanairship/android-library/files/568552/airship_crash.txt)

thanks

**Comment by rlepinski** [comment] 2016-11-03 16:43
@prometheus-xiao Is this limited to a select few devices and/or os versions? How many crashes are you seeing? Total audience size? If you could send me the full crashlytic report that would be helpful.

Are you including google play services location module?

**Comment by prometheus-xiao** [comment] 2016-11-10 06:49
@rlepinski thanks for your response, for you questions, I'm sure I added google play services location module, please check below, this is what I used in my project.
`compile 'com.google.android.gms:play-services-location:9.4.0'`

also I attached 2 images, maybe they are helpful for you.

- my app info
![my_app_info](https://cloud.githubusercontent.com/assets/21022669/20167160/8c658b80-a754-11e6-827f-e00073e5aeb9.png)

- location service crash issue info
![airship_location_service_crash](https://cloud.githubusercontent.com/assets/21022669/20167151/7bf157b6-a754-11e6-934e-f4795975150b.png)

**Comment by rlepinski** [comment] 2016-11-10 22:24
@prometheus-xiao It appears that the crash rates are dropping. I have a feeling that this is due to Google Play Services bug that will go away on its own as devices are updated. The only thing I can do is wrap the bundle access in a try/catch statement, which is not the best workaround.

**Comment by prometheus-xiao** [comment] 2016-11-11 01:11
@rlepinski  that's ok, I think location service is not the necessary service of airship. user should still be able to use app even if there is problem of location service, so I think the way to fix this issue you said is better than now. 

but there is another problem, we are using the Airship version **7.3.0**, because the **minSdkVersion** of airship library is updated to 16 from version **8.0.0**, we can't update our app's **minSdkVersion** to be 16 now. can you please fix this issue for the version **7.3.0**?

thanks

**Comment by rlepinski** [comment] 2016-11-11 01:43
@prometheus-xiao Do you have a large audience still running 4.0? ICS is over 4 years old and has the same number of users as gingerbread (1.3%).

**Comment by prometheus-xiao** [comment] 2016-11-11 01:56
@rlepinski sorry for that, the **minSdkVersion** of all our apps are 15, some app's **minSdkVersion** are decided by our client, I know there is just few user used 15, but we have about 3-4 projects used airship library. if we are going to change minSdkVersion, we need check it with client one by one. 

so if you can fix it on version 7.3.0, that will be great. thanks

**Comment by rlepinski** [comment] 2016-11-11 02:37
I'll work on it tomorrow. Going to do a 8.0.x release with support for API 14+

**Comment by prometheus-xiao** [comment] 2016-11-11 03:28
thank you very much.

**Comment by rlepinski** [comment] 2016-11-11 22:53
@prometheus-xiao Fixed in 8.0.4. minSDKVersion is now set to 15.

**Closed by rlepinski** 2016-11-11 22:53 UTC

**Comment by prometheus-xiao** [comment] 2016-11-14 01:32
got it, thanks

**Comment by prometheus-xiao** [comment] 2016-12-22 02:58
@rlepinski we released our new build with Airship library version 8.0.4, but we still got this crash above, I checked code, looks like it is caused by the line 281 of the class below: 
[https://github.com/urbanairship/android-library/blob/master/urbanairship-sdk/src/main/java/com/urbanairship/location/LocationService.java#L281](https://github.com/urbanairship/android-library/blob/master/urbanairship-sdk/src/main/java/com/urbanairship/location/LocationService.java#L281)

thanks for your help last time, I think you fixed the issue on line 294 last time, but it is crashed on line 281 now. can you please fix it ?

**Comment by hcrowell** [comment] 2016-12-22 18:41
Hi @prometheus-xiao , Thank you for bringing this to our attention. Upon which android versions is this crash occurring? Is it still occurring in only the Samsung & ASUS devices? What is the frequency of this crash? I am trying to reproduce this issue for internal testing, but cannot reproduce on our existing test devices. Also, can you try our latest UA 8.2.3 SDK (minSDKVersion set to 15) and let us know if you can reproduce this crash? Thank you!

**Comment by hcrowell** [comment] 2016-12-22 21:40
Hi @prometheus-xiao , We just released UA 8.2.4 SDK where wrapped the code around try/catch statement. Please try the latest 8.2.4 SDK release. Thank you.

**Comment by prometheus-xiao** [comment] 2016-12-26 03:38
Hi @hcrowell , I can't reproduce this issue too, I just got the crash report on Fabric. looks like now it is only reproduced on OS 4.4.2. 
![fabric_locationservice_crash](https://cloud.githubusercontent.com/assets/21022669/21474785/d80eb8bc-cb5e-11e6-9825-016dc939c06c.png)

I will update Airship library to version 8.2.4, but I can't tell if the issues is fixed or not now. I need wait to release the next build of our app in future, I will keep an eye on it.  thanks.
