### ISSUE TITLE
Set the `namedUser` fails with 400 if I do it immediately after I receive the `AirshipReadyCallback`

### ISSUE THREAD

**Issue by StefMa** [urbanairship/android-library#148] opened 2020-04-21 14:02 UTC
# Preliminary Info

### What Airship dependencies are you using?

```
implementation 'com.urbanairship.android:urbanairship-fcm:12.2.4'
```

### What are the versions of any relevant development tools you are using?

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4

# Report
When I initialize the Airship SDK at a later point (calling `takeOff` not in my `Application` but sometime later) and then setting the `namedUser` immediately **after** I receive the `AirshipReadyCallback` the airship backend answer (nearly 99% of the time) with an `400` status code.

The issue is not about the status code but rather that I can not handle this error in some way.
There is no `Listener` or `Handler` or something like this which can I use to detect that setting the `namedUser` failed (and therefore I react on this and trigger the call again).

### What unexpected behavior are you seeing?

I see an `400` status code while setting the `namedUser` even if the SDK tells me that it is **Ready**.

### What is the expected behavior?

I wouldn't expect an error in the SDK <-> Airship backend communication if the SDK tells me that it is ready.
But of course, error happens. So I would expect that if I get at least notified about errors so that I can handle them properly.

### What are the steps to reproduce the unexpected behavior?

In your `Application.onCreate` do the following:
```kotlin
val airshipConfigOptions = AirshipConfigOptions.Builder()
  ... // Configuration
  .build()

  UAirship.takeOff(this, airshipConfigOptions) { 
    it.namedUser.id = "something"
  }
}
```

Checkout the `LogCat`. You'll see something like:
```
 Update named user failed with status: 400
```

### Do you have logging for the issue?

<details>
<summary> Expand me for logs </summary>

```
Airship taking off!
Airship log level: 3
UA Version: 12.2.4 / App key = [TOP_SECRET] Production = false
Setting platform to android for push provider: FCM Push Provider
Using push provider: FCM Push Provider
RichPushInbox - Updating user.
Migrating push enabled preferences
Setting user notifications enabled to false
Push is now enabled. You can continue to toggle the opt-in state by enabling or disabling user notifications
AutomationDataManager - Creating automation database
NotificationChannelRegistryDataManager - Creating database
AutomationDataManager - Automation database created
RemoteDataStore - Creating database
Automation - Updating triggers with type: 8
Airship - Setting data collection enabled to true
Airship ready!
AutomationDataManager - Creating automation database
AutomationDataManager - Automation database created
Automation - Updating triggers with type: 8
InAppRemoteDataObserver - Finished processing messages.
Analytics - New session: [TOP_SECRET]
Analytics - Disabled ignoring event: app_foreground
Automation - Updating triggers with type: 1
Automation - Updating triggers with type: 1
InboxJobHandler - User has not been created, canceling messages update
Locale: de_DE.
Locales: [de_DE,en_US].
System Locale: de_DE.
Received remote data response: {"ok":true,"payloads":[{"type":"app_config","timestamp":"[TOP_SECRET]","data":{}},{"type":"app_config:android","timestamp":"[TOP_SECRET]","data":{}},{"type":"in_app_messages","timestamp":"[TOP_SECRET]","data":{"in_app_messages":[]}}]}
InAppRemoteDataObserver - Finished processing messages.
The channel ID does not exist. Will retry when channel ID is available.
Remote data not modified since last refresh
PushManagerJobHandler - Push registration updated.
Airship channel created: [TOP_SECRET]
RichPushInbox - Updating user.
Update named user failed with status: 400
Created Rich Push user: [TOP_SECRET]
RichPushUser - Setting Rich Push user: [TOP_SECRET]
Refreshing inbox messages.
Received 0 inbox messages.
```

</details>

**Comment by BrianBatchelder** [comment] 2020-04-21 15:04
@StefMa Thank you for the report. We will look into it ASAP.

**Comment by rlepinski** [comment] 2020-04-21 15:26
@StefMa The problem is the channel is not created yet so the payload is invalid. We will fix this in the next patch. All retrying and error handling is handled for you by the SDK, and luckily it should try again once the channel is created so there is no need to do anything, but you will see that error on first run before the channel is created. If you want to prevent the error on your current version you could use this workaround:

```
UAirship.takeOff(this, airshipConfigOptions) {
    if (it.channel.id == null) {
        it.channel.addChannelListener(object: AirshipChannelListener {
            override fun onChannelCreated(channelId: String) {
                it.namedUser.id = "something"
            }

            override fun onChannelUpdated(channelId: String) {}
        })
    } else {
        it.namedUser.id = "something"
    }
}
```

**Comment by rlepinski** [comment] 2020-04-21 15:57
@StefMa Ok, its actually not the SDK. Seems like a backend issue that we are investigating. Github is having issues and not letting me edit my previous comment. Please ignore it.

**Comment by rlepinski** [comment] 2020-04-22 00:23
@StefMa Should be fixed. Please let us know if you continue to see the issue.

**Closed by rlepinski** 2020-04-22 00:23 UTC

**Comment by StefMa** [comment] 2020-04-23 11:50
That was fast.
Thank you for the quick fix. It worked (testet in 5 times 🙃).

But I have an additional question to one of your comments:
> All retrying and error handling is handled for you by the SDK

Does this mean that I can more or less trust the SDK that it will "always work" and handle errors by itself? There is no plan (ever) to expose a Listener/Handler to catch errors? 🤔

**Comment by BrianBatchelder** [comment] 2020-04-23 15:28
We handle as many errors as we can. There are certain errors that the app can help with, and in those cases, we expose listeners/handlers. In this case, this API is between our SDK and our servers, so we can predict and handle all of the errors.
