### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#37] opened 2017-11-09 19:38 UTC
Hello,
I am having problem in my application where the button texts are not respecting the language of the phone. My phone is on pt-br but the texts shown appear in English. Any idea?

@rlepinski

**Comment by rlepinski** [comment] 2017-11-09 19:39
@halysongoncalves Notification action buttons? Could you post a screen shot? What SDK version?

**Comment by halysongoncalves** [comment] 2017-11-09 19:46
I am using version 8.9.4 with the language pt-br.

![locale](https://user-images.githubusercontent.com/5872045/32626223-ecc2f752-c575-11e7-9011-df1b63549114.png)
![strings](https://user-images.githubusercontent.com/5872045/32626224-ece1b160-c575-11e7-98b2-b73028233c54.png)

**Comment by rlepinski** [comment] 2017-11-09 20:51
We provide localization for that string - https://github.com/urbanairship/android-library/blob/master/urbanairship-sdk/src/main/res/values-pt/strings.xml#L12

Your languageTag in the debugger is set to "und", not sure if that has something to do with it. Do any of your other strings work? Do you have `shrinkResources` enabled?

**Comment by halysongoncalves** [comment] 2017-11-09 20:57
I did not enable shrinkResource and all strings are displayed English.

**Comment by rlepinski** [comment] 2017-11-09 20:58
Even your custom strings are being displayed in english, even in your own activities?

**Comment by halysongoncalves** [comment] 2017-11-09 21:00
All strings are displayed from the urban. My application's string is being displayed in en

**Comment by rlepinski** [comment] 2017-11-09 21:10
I am unable to reproduce. It works for me:
![device-2017-11-09-130637](https://user-images.githubusercontent.com/3967591/32629773-299b700e-c54f-11e7-80bc-ab3e9e3017bc.png)

When I check my current locale after setting my phone to "pt-br", it shows a proper language tag:
<img width="549" alt="screen shot 2017-11-09 at 1 08 32 pm" src="https://user-images.githubusercontent.com/3967591/32629797-44748762-c54f-11e7-8839-19afdfcba2f2.png">

This does not seem like its related to our SDK. So I am going to close it.

**Closed by rlepinski** 2017-11-09 21:10 UTC
