### ISSUE TITLE
Excessive log messages after upgrade to either 8.8 or 8.9

### ISSUE THREAD

**Issue by KennyGoers** [urbanairship/android-library#26] opened 2017-10-03 16:40 UTC
I just upgraded from 8.5.1 to 8.8.4 (also tried 8.9.0), suddenly I'm getting a flood of the following messages in the log:

Thoughts?

10-03 11:33:39.428 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:39.431 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:39.514 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:39.517 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:39.585 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:39.590 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:39.698 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:39.702 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:39.784 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:39.786 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:39.878 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:39.881 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:39.985 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:39.988 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:40.082 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:40.085 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:40.177 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:40.182 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:40.271 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:40.273 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:40.377 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:40.380 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:40.946 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:40.947 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:41.085 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:41.088 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:41.458 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:41.461 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:41.544 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:41.545 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:41.639 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:41.641 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:41.736 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:41.738 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:41.819 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:41.821 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:41.909 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:41.911 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.008 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.012 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.123 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.125 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.207 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.209 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.292 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.294 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.371 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.374 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.453 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.457 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.552 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.554 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.634 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.637 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.726 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.728 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.803 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.806 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.891 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.893 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:43.967 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:43.969 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.062 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.064 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.166 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.168 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.248 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.251 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.331 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.332 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.420 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.424 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.511 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.514 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.611 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.613 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.720 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.723 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.796 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.798 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.873 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.876 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:44.956 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:44.959 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:45.066 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:45.069 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:45.140 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:45.142 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:45.221 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:45.223 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:45.332 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:45.334 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:45.461 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:45.463 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:45.537 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:45.540 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:45.638 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:45.641 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:45.796 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:45.797 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:45.904 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:45.907 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:45.977 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:45.979 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:46.062 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:46.064 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:46.163 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:46.165 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:46.273 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:46.275 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:46.369 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:46.372 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:46.453 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:46.455 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
10-03 11:33:46.547 5142-5264/? I/Zubie-QA - UALib: Channel registration succeeded with status: 200
10-03 11:33:46.550 5142-5142/? D/Zubie-QA - UALib: UrbanAirshipMessageReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED

**Comment by rlepinski** [comment] 2017-10-03 16:54
You can change the log level through airship config options. `developmentLogLevel = INFO'. However I am concerned why your channel registration is updating constantly. Can you actually set the log level to `VERBOSE` and report back with the logs?

**Comment by KennyGoers** [comment] 2017-10-03 16:56
I can, this doesn't happen when I downgrade back to 8.5.1. Another point is that this is in the emulator, but that hasn't been an issue.

**Comment by KennyGoers** [comment] 2017-10-03 16:57
I just checked, that is VERBOSE, I enable VERBOSE for none production builds.

**Comment by rlepinski** [comment] 2017-10-03 17:00
@KennyGoers Could you provide me the entire log output instead of filtered logs? Make sure not to post any secrets. If you would rather, email me them at mobileteam@urbanairship.com

**Comment by KennyGoers** [comment] 2017-10-03 17:02
I'll email to you

**Comment by rlepinski** [comment] 2017-10-03 17:14
Cool, once I get the logs I will look into it immediately.  I am unable to reproduce the issue on my machine so I am very curious what is going on in that emulator.

**Comment by KennyGoers** [comment] 2017-10-03 17:59
Well now I can't get it to happen again, was happening in two different emulators (Android 25 and 26), possibly data or something else from moving back and forth between versions (8.5.1 -> 8.9.0 -> 8.5.1 -> 8.9.0) ? I'll continue to monitor and watch the logs, but this has happened to me several times, just hadn't taken the time to report as it didn't have a perceivable result other than flooding the logs.

**Comment by KennyGoers** [comment] 2017-10-03 20:09
I have logs for you, I got it to happen again. Can you give me your email address again?

**Comment by rlepinski** [comment] 2017-10-03 20:10
Awesome! mobileteam@urbanairship.com

**Comment by rlepinski** [comment] 2017-10-03 20:21
@KennyGoers It looks like the logs are DEBUG not VERBOSE. Could you double check you are not filtering your logcat for DEBUG and above? You should see message that match `V/Zubie-QA - UALib:`. Also how are you registering the `UrbanAirshipMessageReceiver` class?

**Comment by rlepinski** [comment] 2017-10-09 21:05
@KennyGoers Could your provide what build tools, android gradle plugin, and any other build related flags you are using?

**Comment by rlepinski** [comment] 2017-10-09 22:38
@KennyGoers We just released 8.9.1 with a potential fix to your issue. Could you try it out and report back? Thanks

**Comment by KennyGoers** [comment] 2017-10-10 01:28
I will, thanks. I was out all day so just saw your message.

**Comment by rlepinski** [comment] 2017-10-17 16:13
@KennyGoers did 8.9.1 resolve your issue? We had two patch release since 8.9.1 and we would recommend updated to 8.9.3.

**Comment by rlepinski** [comment] 2017-10-24 16:56
Closing for now

**Closed by rlepinski** 2017-10-24 16:56 UTC
