### ISSUE TITLE
com.urbanairship.push.notifications.NotificationChannelRegistryDataManager.getChannel

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#144] opened 2020-02-19 13:17 UTC
Hello,

We have identified crash in `com.urbanairship.push.notifications.NotificationChannelRegistryDataManager.getChannel` that has affected our users.
 
![Captura de Tela 2020-02-19 às 10 17 12](https://user-images.githubusercontent.com/5872045/74837808-0f995080-5301-11ea-8ad1-948657c3bf8e.png)

![Captura de Tela 2020-02-19 às 10 17 15](https://user-images.githubusercontent.com/5872045/74837812-11631400-5301-11ea-8a7c-012cf66b5abf.png)

![Captura de Tela 2020-02-19 às 10 17 26](https://user-images.githubusercontent.com/5872045/74837814-11fbaa80-5301-11ea-8fb6-0e81cd17c514.png)

`Fatal Exception: android.database.sqlite.SQLiteDatabaseCorruptException
database disk image is malformed (code 11)
android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow (SQLiteConnection.java)
android.database.AbstractCursor.moveToFirst (AbstractCursor.java:237)
com.urbanairship.push.notifications.NotificationChannelRegistryDataManager.getChannel (NotificationChannelRegistryDataManager.java:129)
com.urbanairship.push.notifications.NotificationChannelRegistry$1.run (NotificationChannelRegistry.java:93)
com.urbanairship.util.SerialExecutor$1.run (SerialExecutor.java:40)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
com.urbanairship.util.AirshipThreadFactory$1.run (AirshipThreadFactory.java:49)
java.lang.Thread.run (Thread.java:841)Fatal Exception: java.lang.IncompatibleClassChangeError
The method 'void com.urbanairship.reactive.Observable$ObservableTracker$1.a(java.lang.Exception)' was expected to be of type static but instead was found to be of type virtual (declaration of 'com.urbanairship.reactive.Observable' appears in /data/app/com.globo.globotv-1/base.apk:classes4.dex)
com.urbanairship.reactive.Observable.subscribeOn (Observable.java:344)
com.urbanairship.automation.TriggerObservables.newSession (TriggerObservables.java:76)
com.urbanairship.automation.AutomationEngine.createEventObservable (AutomationEngine.java:730)
com.urbanairship.automation.AutomationEngine.restoreCompoundTriggers (AutomationEngine.java:779)
com.urbanairship.automation.AutomationEngine.start (AutomationEngine.java:330)
com.urbanairship.automation.Automation.init (Automation.java:76)
com.urbanairship.UAirship.init (UAirship.java:748)
com.urbanairship.UAirship.executeTakeOff (UAirship.java:409)
com.urbanairship.UAirship.access$000 (UAirship.java:61)
com.urbanairship.UAirship$2.run (UAirship.java:368)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
com.urbanairship.util.AirshipThreadFactory$1.run (AirshipThreadFactory.java:49)
java.lang.Thread.run (Thread.java:761)`

**Comment by BrianBatchelder** [comment] 2020-02-19 21:50
Duplicate of #141.

**Closed by BrianBatchelder** 2020-02-19 21:50 UTC

**Comment by halysongoncalves** [comment] 2020-03-03 16:32
Hi @BrianBatchelder,

The error is different from the issue #141

**Comment by halysongoncalves** [comment] 2020-03-03 16:32
Fatal Exception: android.database.sqlite.SQLiteDatabaseCorruptException database disk image is malformed (code 11)

**Comment by halysongoncalves** [comment] 2020-03-03 16:33
Currently this error happens because users install our application on pirated devices

**Comment by rlepinski** [comment] 2020-03-03 17:28
We will catch this exception on the next release, but the SDK will not function properly on those devices.
