### ISSUE TITLE
App get crash Take off must be called before shared()

### ISSUE THREAD

**Issue by ntanduc2288** [urbanairship/android-library#107] opened 2019-01-08 00:13 UTC
Sometimes I get that error when starting the app.

**UrbanAirship version: 9.5.2**

**I'm used custom AutoPilot**
```
public class CustomAutoPilot extends Autopilot {
    private final String DEVELOPMENT_APP_KEY = "<key>";
    private final String DEVELOPMENT_APP_SECRET = "<key>";
    private final String PRODUCTION_APP_KEY = "<key>";
    private final String PRODUCTION_APP_SECRET = "<key>";
    private final String FCM_SENDER_ID = "<key>";

    @Nullable
    @Override
    public AirshipConfigOptions createAirshipConfigOptions(@NonNull Context context) {
        AirshipConfigOptions airshipConfigOptions = new AirshipConfigOptions.Builder()
                .setInProduction(!BuildConfig.DEBUG)
                .setDevelopmentAppKey(DEVELOPMENT_APP_KEY)
                .setDevelopmentAppSecret(DEVELOPMENT_APP_SECRET)
                .setProductionAppKey(PRODUCTION_APP_KEY)
                .setProductionAppSecret(PRODUCTION_APP_SECRET)
                .setFcmSenderId(FCM_SENDER_ID)
                .setNotificationChannel("customChannel")
                .build();

        return airshipConfigOptions;
    }
}
```

**Here is Manifest file.**
`<meta-data android:name="com.urbanairship.autopilot"
            android:value="<path>.CustomAutoPilot"/>`

**And here is the code which is called in onCreate() method of the Application class**
```
private void initializeUrbanAirship() {
        if(!UAirship.isTakingOff()){
            PushManager pushManager = UAirship.shared().getPushManager(); **// It crashes at this line** 
            final String channelId = pushManager.getChannelId();
            UberLog.i("UrbanAirship", "Urban Airship channelId: " + channelId);

            pushManager.setNotificationFactory(new ReiPushNotificationFactory(this));
            TagManager.get().initPushNotificationTags();

            UALocationManager locationManager = UAirship.shared().getLocationManager();

            locationManager.setBackgroundLocationAllowed(false);
            locationManager.setLocationUpdatesEnabled(true);
            pushManager.setPushEnabled(true);
            pushManager.setUserNotificationsEnabled(true);
        }

    }
```

Could you please help me to double check it?

**Comment by ntanduc2288** [comment] 2019-01-08 00:43
Yes, I did. I put it under Application tag. Note that it just occurs sometimes.

The weird thing is after I close the "force stop" popup, the app is still open and I can get the channel ID

**Comment by rlepinski** [comment] 2019-01-08 01:39
@ntanduc2288 Are you using multidex? Could you provide statistics on the crashes? What devices, how often, etc... ? Is this something you can reproduce locally?

Normally our content provider will kickoff autopilot and that is suppose to run before application onCreate. We can add some code to work around that issue if its just the content provider not loading in time.

First, in your application onCreate add a call to autopilot:
```
    @Override
    public void onCreate() {
        super.onCreate();
        Autopilot.automaticTakeOff(this);
        ....
   }
```
That will make sure autopilot is called even if for whatever reason the provider fails to load it.

Next, remove the check for `UAirship.isTakingOff()`, its not what you want. shared() will work as long as either autopilot is called or takeOff is called manually.

You can actually move all of that setup logic to your autopilot class to clean things up:

```
    @Override
    public void onAirshipReady(UAirship airship) {
        PushManager pushManager = airship.getPushManager(); 
        final String channelId = pushManager.getChannelId();
        UberLog.i("UrbanAirship", "Urban Airship channelId: " + channelId);

        pushManager.setNotificationFactory(new ReiPushNotificationFactory(this));
        TagManager.get().initPushNotificationTags();

        UALocationManager locationManager = airship.getLocationManager();

        locationManager.setBackgroundLocationAllowed(false);
        locationManager.setLocationUpdatesEnabled(true);
        pushManager.setPushEnabled(true);
        pushManager.setUserNotificationsEnabled(true);
    }
```

**Comment by ntanduc2288** [comment] 2019-01-08 17:52
**Here is crash log:**
`java.lang.RuntimeException: Unable to create application <packageName>.Application: java.lang.IllegalStateException: Take off must be called before shared()
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalStateException: Take off must be called before shared()
        at com.urbanairship.UAirship.shared(UAirship.java:152)
        at <packageName>.Application.initializeUrbanAirship(Application.java:332)
        at <packageName>.Application.onCreate(Application.java:144)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)`

**My app is using multidex.**

**Step to reproduce:**
1. Install app
2. Run app -> then press back button then open the app again
3. Repeat step #2 several times -> app is crashed

**Devices:**
- Motorola NEXUS (OS 5.1)
- Blackberry key 2 (OS 8.1)
- Samsung genymotion (OS 8.0)

I will give it a shot as your suggestions

**Comment by rlepinski** [comment] 2019-01-10 19:00
@ntanduc2288 Any luck?

**Comment by rlepinski** [comment] 2019-01-18 18:43
Closing for now. Please comment if you are still having issues.

**Closed by rlepinski** 2019-01-18 18:43 UTC

**Comment by SaikCaskey** [comment] 2019-09-25 12:57
I can recreate this, and am getting some random crashes on some devices. Do you know the cause? Why is this closed?

**Comment by WalidMaata** [comment] 2020-03-10 22:52
I got the same issue , there is any suggestion except the work around `  Autopilot.automaticTakeOff(this);` so weird this issue closed without any explanation ?

**Comment by BrianBatchelder** [comment] 2020-03-10 23:15
Please contact [Airship Support](https://support.airship.com).
