### ISSUE TITLE
Error: Couldn't expand RemoteViews on Android 4.4.4

### ISSUE THREAD

**Issue by guntherhoppe** [urbanairship/android-library#11] opened 2017-04-27 17:00 UTC
We watch recurring crashes of our LIVE app on Android 4.4.4 devices only. It looks like a problem while displaying the push message in notification bar. I appended the stack trace below.

We use the current version 8.3.2 of the Urban Airship SDK.

---
04-25 07:52:17.835 I/dalvikvm( 1942): Could not find method android.content.Context.checkSelfPermission, referenced from method com.urbanairship.analytics.EventApiClient.getLocationPermission
04-25 07:52:17.835 W/dalvikvm( 1942): VFY: unable to resolve virtual method 453: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
04-25 07:52:17.835 D/dalvikvm( 1942): VFY: replacing opcode 0x6e at 0x000c
04-25 07:52:18.285 D/AndroidRuntime( 1942): Shutting down VM
04-25 07:52:18.285 W/dalvikvm( 1942): threadid=1: thread exiting with uncaught exception (group=0x41e53d58)
04-25 07:52:18.295 E/ACRA    ( 1942): ACRA caught a RemoteServiceException for XYZ
04-25 07:52:18.295 E/ACRA    ( 1942): android.app.RemoteServiceException: Bad notification posted from package XYZ: Couldn't expand RemoteViews for: StatusBarNotification(pkg=XYZ user=UserHandle{0} id=1013 tag=null score=0: Notification(pri=0 contentView=XYZ/0x109006a vibrate=default sound=default defaults=0x3 flags=0x10 kind=[null]))
04-25 07:52:18.295 E/ACRA    ( 1942): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
04-25 07:52:18.295 E/ACRA    ( 1942): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-25 07:52:18.295 E/ACRA    ( 1942): 	at android.os.Looper.loop(Looper.java:136)
04-25 07:52:18.295 E/ACRA    ( 1942): 	at android.app.ActivityThread.main(ActivityThread.java:5034)
04-25 07:52:18.295 E/ACRA    ( 1942): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-25 07:52:18.295 E/ACRA    ( 1942): 	at java.lang.reflect.Method.invoke(Method.java:515)
04-25 07:52:18.295 E/ACRA    ( 1942): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
04-25 07:52:18.295 E/ACRA    ( 1942): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
04-25 07:52:18.295 E/ACRA    ( 1942): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by rlepinski** [comment] 2017-04-27 17:03
Are you using a custom notification factory? Is it actually crashing or logging an error? Are you able to reproduce at all?

**Comment by guntherhoppe** [comment] 2017-04-27 17:17
We don't use a custom notification factory. We set a notificationIcon and a notificationAccentColor in the properties file only. Unfortunately I'm not able to reproduce this (haven't an Android 4.4.4 device). The error was reported by our crash tool.

Our init class:

```
public class UAAutoPilot extends Autopilot {

    @Nullable
    @Override
    public AirshipConfigOptions createAirshipConfigOptions(@NonNull Context context) {
        return new AirshipConfigOptions.Builder()
            .applyDefaultProperties(context)
            // set production mode from build config
            .setInProduction(BuildConfig.UA_IN_PRODUCTION)
            .build();
    }

    @Override
    public boolean allowEarlyTakeOff(@NonNull Context context) {
        return true;
    }
}
```

Enable/disable push notifications from witrhin app is done this way:

```
/**
 * Helper to enable/disable Push Messages
 *
 * @param tags
 */
public static void setEnabled(Set<String> tags) {
	if (UAirship.isFlying()) {
		UAirship.shared().getPushManager().setPushEnabled(!tags.isEmpty());
		UAirship.shared().getPushManager().setUserNotificationsEnabled(!tags.isEmpty());

		UAirship.shared().getPushManager().setTags(tags);
	}
}
```

**Comment by rlepinski** [comment] 2017-04-27 17:24
What type of resource are you using for the notification icon? Is it a vector image by any chance?

**Comment by guntherhoppe** [comment] 2017-04-27 17:27
No - it is a PNG (32 bit) with transparencies.

**Comment by rlepinski** [comment] 2017-04-27 17:32
Well, our SDK is not doing anything that exciting or unique when building notifications - https://github.com/urbanairship/android-library/blob/master/urbanairship-sdk/src/main/java/com/urbanairship/push/notifications/NotificationFactory.java#L250

We use standard APIs, so this is going to be hard to figure out. Could you provide crash statistics (% audience, device models, etc...), airship config (without keys), and any icons are you are using? 

The raw data from the crash report would be helpful, if you can share it. My email is ryan.lepinski@urbanairship.com if you would rather email the info.

**Comment by guntherhoppe** [comment] 2017-05-02 11:39
@rlepinski: I sent you the requested informations to your email address. Thanks for your help.

**Comment by rlepinski** [comment] 2017-05-02 18:20
@guntherhoppe Everything you sent looks fine. What kind of notifications are you sending? Are you doing any big picture images?

**Comment by guntherhoppe** [comment] 2017-05-03 12:56
@rlepinski: We send a pretty standard notification with a title and a lead text (without an additional image). The notifications contains a payload with a single custom key (id: 12345) which we process in the UAIntentReceiver (see the code I sent to you).

**Comment by rlepinski** [comment] 2017-05-04 21:22
@guntherhoppe I don't see anything that would cause an issue. No custom layouts, your icons are the correct size, and no big images. I do not believe this is an issue with our SDK, but instead with those 2 devices.  The crash is not taking place in an area that we can catch, so the only other work around would be to disable push notifications for those devices. 

I am going to close this issue as not reproducible, please reopen if you find any new info or if the number of crashes for unique users starts to grow.

**Closed by rlepinski** 2017-05-04 21:22 UTC

**Comment by barnhill** [comment] 2018-04-30 18:49
@rlepinski we are getting this in our app and seeing it VERY regularly but usually only when the app is upgraded to a newer version on the device.  It doesnt seem specific to any device in particular.  Also I noticed above that you asked about using a custom NotificationFactory and we are but its very simple.

We are using UA 9.0.1 and here is a copy of the exception:

android.app.RemoteServiceException: Bad notification posted from package X.Y.Z: Couldn't expand RemoteViews for: StatusBarNotification(pkg=X.Y.Z user=UserHandle{0} id=2922008 tag=null key=0|X.Y.Z|2922008|null|10087: Notification(pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x10 color=0xff004a8e vis=PRIVATE))

We have a very large user base and we are seeing this very often but it seems to be clustered around application upgrades.  If I need to log another issue let me know and Ill be glad to do so.  It just seemed to be VERY similar to this issue.

**Comment by rlepinski** [comment] 2018-04-30 19:47
@barnhill Can you provide statistics on what devices are being hit by the crash, such as OS version, devices, etc... ? 

This does not seem to be an Urban Airship issue but instead an Android platform issue. Our SDK just takes that notification you build and hands it off to the OS. We are not adding any remote views or anything to the notification that will cause it to fail to render. The only thing we do is wrap the content intent & delete intent so we can track when the notification is being interacted with.

Its hard to say what the exact problem is, but based on my research it seems the issue is around the  resource IDs changing during app updates. Usually the apps notification are cleared during updates, but it seems some manufacturers tried to restore those notifications, or maybe skipped the clear step, and when the notification is being rendered it throws an exception.

Some people seem to have had success with setting a fixed resource Ids for any resources they use when building the notification:

- https://stackoverflow.com/questions/9348614/what-is-the-use-of-the-res-values-public-xml-file-on-android
- https://stackoverflow.com/questions/25317659/how-to-fix-android-app-remoteserviceexception-bad-notification-posted-from-pac

I can't find any documentation on https://developer.android.com/ about the use of public.xml in an app, but it might be worth a shot. 

Please report back with the crash info if you can.

**Comment by barnhill** [comment] 2018-04-30 20:00
Device Models reporting this issue:
-----------------
SAMSUNG SM-T230NU
MOTOROLA XT1585, XT1650
SAMSUNG SM-T713
SAMSUNG SM-T710
SAMSUNG SM-T813
SAMSUNG SM-J727T1
SAMSUNG SM-J727T
SAMSUNG SM-J327V
SAMSUNG SM-G950U
SAMSUNG SM-T580
SAMSUNG SM-G955U
SAMSUNG SM-P580
SAMSUNG SM-T810, SM-T820, 
SAMSUNG SAMSUNG-SM-J727A, SM-J727AZ, SM-T827V
MOTOROLA MOTO G5, MOTO G5 Plus
MOTOROLA MOTO G4
MOTOROLA XT1575
LGE LGMS428, LGMP450, LG-H872, LG-TP450, LG-M150, LGE-VS500, LG-M322, LG-US701, LG-M255, LG-H901

OS versions reporting this:
-----------------
4.4.2
7.0

**Comment by rlepinski** [comment] 2018-04-30 20:58
@barnhill Any chance you can try the public.xml change to see if that helps? If you figure out your existing resource ids for the resources that you are using, you should be able to see if it helps in the next update.

**Comment by barnhill** [comment] 2018-04-30 23:05
Going to test that out tomorrow and if everything looks good with that I'll
report back after the next release.

**Comment by rlepinski** [comment] 2018-05-01 20:30
Bummer :(.  I am not sure what else we can do here except file an android OS issue. Ill let you know if I find any other info on this issue.

**Comment by barnhill** [comment] 2018-05-02 00:05
There is an Android OS ticket that got closed as will not fix around this.
There has to be a solution to this that we aren't thinking of.  Have you
tried the public.xml route on a test app to make sure it's not something I
did wrong?

**Comment by rlepinski** [comment] 2018-05-02 16:05
@barnhill looks like it has been removed in newer versions of gradle. I have potentially two other solutions:

- Register for ACTION_MY_PACKAGE_REPLACED broadcasts and clear notifications.
- Move all your notifications resources to a module build it, and pull in the AAR. Only rebuild the module when your icons change.

The ACTION_MY_PACKAGE_REPLACED seems way more convenient if it works, but since I am unable to reproduce the crash its hard to say when the remote view exception is occurring.

**Comment by barnhill** [comment] 2018-05-30 16:52
@rlepinski Ill try this in an upcoming release and HOPEFULLY it will address the issue ... Ill make sure to report back.

**Comment by barnhill** [comment] 2018-09-25 14:14
Can't get our architect to agree to put this in our code. :(

**Comment by rlepinski** [comment] 2018-09-25 16:48
@barnhill Could you provide updated crash data? Is the crash numbers dropping? Any new OS versions?

**Comment by vicpinm** [comment] 2018-09-27 09:33
@rlepinski I have the same problem with Huawey P8 Lite and Android 5.0. I don't understand why your solution with  ACTION_MY_PACKAGE_REPLACED broadcast could solve the problem. If you have a visible notification, when the app is updated, that notification is automatically closed by the system, and when you open your updated app, it would created a new notification, but the old one does not appear anywhere, right?

**Comment by Mouadabdelghafouraitali** [comment] 2019-05-16 01:00
@vicpinm hi, I have the same issue with Huawei P8 Lite with Android 5.0 how I can resolve this issue, please ??

**Comment by barnhill** [comment] 2019-05-16 03:54
This hasnt been fixed but they marked it as closed ... for some reason.

**Comment by rlepinski** [comment] 2019-05-16 22:57
@barnhill We marked it as closed because no one is able to reproduce this issue and it seems more likely it's either an android / manufacturer implementation issue. Other reports online about remote views usually have to do with posting a custom notification with invalid resource values. Our SDK is not doing any of those things.

@vicpinm Without proper reproduction steps we are just guessing whats going on here. Usually the system will clear all notifications when the app is updated, but for whatever reason it seems like that step is causing the exception on some devices. My thought was maybe the phone is actually trying to restore those notifications on behave of the app or is not clearing them in time of the update. Having the update receiver was just a potential solution, but i have no idea if it would of prevented the exception.

@Mouadabdelghafouraitali Could you provide more details:

- stack trace
- % of crashes
- Does this only happen on upgrades?
- Are you only using Airship for notifications? Are you posting local notifications?

**Comment by barnhill** [comment] 2019-05-16 23:25
@rlepinski just throwing this out there.  Is it possible this happens with notifications around upgrade times?  That seems to be when we see these pop up.  Could it be trying to restore notifications that contain resource ids that have changed ids and the id its trying to restore no longer exists?

**Comment by rlepinski** [comment] 2019-05-17 00:20
@barnhill We do not restore notifications. One signal has a similar issue and they believe it's tied to their restore behavior. Do you post notifications directly or do any restore behavior?

**Comment by barnhill** [comment] 2019-05-17 03:25
Not that Im aware of.

Brad Barnhill
bradbarnhill@hotmail.com
www.bradbarnhill.com

**Comment by ianmcoelho** [comment] 2020-02-20 20:53
Any news on this? We have this bug for at least 3 years and couldn't figure it out yet.

**Comment by BrianBatchelder** [comment] 2020-02-20 21:36
To pursue this further, please contact [Airship Support](https://support.airship.com/).

**Comment by barnhill** [comment] 2020-02-21 23:31
@BrianBatchelder they aren't going to fix this but it's definitely a recurring issue.

**Comment by rlepinski** [comment] 2020-02-21 23:34
This is not an issue with Airship directly. Nothing we can do about this. Airship posts notifications using the standard mechanisms. We do not try to do any weird restore behavior that might lead to this issue. It is a bug in the implementation on those devices, which obviously will not be updated. The best you can do is avoid messaging those devices.

**Comment by barnhill** [comment] 2020-02-21 23:36
Best I could tell the resid of notification icons was changing between builds and during upgrades this caused this issue. I no longer work for the company that had the issue and the new company doesn't use urbanairship so I guess it's resolved 🤣
