### ISSUE TITLE
com.urbanairship.job.JobInfo.toPersistableBundle

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#142] opened 2020-02-19 13:15 UTC
Hello,

We have identified crash in `com.urbanairship.job.JobInfo.toPersistableBundle` that has affected our users.

 
![Captura de Tela 2020-02-19 às 10 14 11](https://user-images.githubusercontent.com/5872045/74837626-aa455f80-5300-11ea-9f3b-85b5bbedbbb5.png)

![Captura de Tela 2020-02-19 às 10 14 15](https://user-images.githubusercontent.com/5872045/74837629-ac0f2300-5300-11ea-90cb-06b22fc387f3.png)

![Captura de Tela 2020-02-19 às 10 14 41](https://user-images.githubusercontent.com/5872045/74837631-aca7b980-5300-11ea-900d-5e7b97e9c048.png)

`Fatal Exception: java.lang.ClassCastException
java.lang.String cannot be cast to java.lang.Object[]
android.util.ArrayMap.allocArrays (ArrayMap.java:173)
android.os.BaseBundle.putBoolean (BaseBundle.java:334)
com.urbanairship.job.JobInfo.toPersistableBundle (JobInfo.java:224)
com.urbanairship.job.AndroidJobScheduler.scheduleJob (AndroidJobScheduler.java:69)
com.urbanairship.job.AndroidJobScheduler.schedule (AndroidJobScheduler.java:45)
com.urbanairship.job.JobDispatcher.dispatch (JobDispatcher.java:95)
com.urbanairship.remotedata.RemoteData.refresh (RemoteData.java:223)
com.urbanairship.remotedata.RemoteData.init (RemoteData.java:163)
com.urbanairship.UAirship.init (UAirship.java:748)
com.urbanairship.UAirship.executeTakeOff (UAirship.java:409)
com.urbanairship.UAirship.access$000 (UAirship.java:61)
com.urbanairship.UAirship$2.run (UAirship.java:368)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
com.urbanairship.util.AirshipThreadFactory$1.run (AirshipThreadFactory.java:49)
java.lang.Thread.run (Thread.java:818)`

**Comment by BrianBatchelder** [comment] 2020-02-19 22:24
This issue is most likely due to disk corruption. The persisted bundle is not unparcelling correctly. It is most likely unrelated to the Airship SDK.

If you would like further assistance, please provide us with the following:
- What Urban Airship dependencies (with versions) are you using in the app versions exhibiting the issue? 
- What are the versions of any relevant development tools you are using?
- Do you have any additional context that might aid in constructing steps to reproduce the issue?

**Comment by halysongoncalves** [comment] 2020-03-03 16:37
1- We are currently using the version: 11.0.5

2- 
    final constraintVersion = '1.1.3'
    final daggerVersion = '2.26'
    final javaxAnnotationVersion = '1.0'
    final javaxInjectVersion = '1'
    final archVersion = '2.0.0'
    final lifecycleVersion = '2.2.0'
    final fragmentkTXVersion = '1.2.0'
    final multidexVersion = '2.0.1'
    final permissionVersion = '3.3.2'
    final fabricVersion = '2.9.1@aar'
    final coroutinesVersion = '1.3.2'
    final playServiceVersion = '16.1.0'
    final firebaseAnalyticsVersion = '17.0.1'
    final firebaseIidVersion = '18.0.0'
    final firebasePerformanceVersion = '17.0.2'
    final playerServiceTagManagerVersion = '16.0.8'
    final viewPager2Version = "1.0.0"
    final materialVersion = "1.1.0-rc01"

    //Player
    final exoPlayerVersion = '2.10.7'
    final interactiveMediaVersion = '3.8.5'
    final playServicesCastVersion = '16.1.2'
    final googleAnalyticsVersion = '16.0.8'
    final playServicesAdsVersion = '15.0.1'

  
    //GloboId
    final globoIdVersion = '1.13.1'
    final firebaseMessageVersion = '18.0.0'
    final playServicesLocationVersion = '16.0.0'
    final playServicesIidVersion = '16.0.1'
    final playServicesAuthVersion = '16.0.1'

    //Http
    final retrofitVersion = '2.6.1'
    final okHttpVersion = '3.12.1'
    final rxJavaVersion = '2.1.16'
    final rxRelayVersion = '2.1.0'
    final rxAndroidVersion = '2.0.2'
    final okioVersion = '1.13.0'

    //Others
    final gsonVersion = '2.8.5'
    final frescoVersion = '1.2.0'
    final picassoVersion = '2.5.2'
    final horizonVersion = '1.3.2'
    final canarinhoVersion = '1.2.0'
    final comScoreVersion = '5.7.3'
    final urbanVersion = '11.0.5'
    final facebookVersion = '4.34.0'
    final appsFlyerVersion = '4.8.19'
    final installReferrerVersion = '1.0'
    final glideVersion = '4.11.0'
    final salesForceVersion = '6.4.0'
    final hawkVersion = '2.0.1'
    final materialCalendarViewVersion = '1.7.0'
    final globocastVersion = '1.8.1'

**Comment by rlepinski** [comment] 2020-03-03 17:34
Will be fixed in the next release.

**Closed** 2020-03-06 17:59 UTC
