### ISSUE TITLE
Andrdoid 4.4.2 not loading inbox message

### ISSUE THREAD

**Issue by toanvc** [urbanairship/android-library#13] opened 2017-05-30 15:22 UTC
Hi guys, my app is using UA version 8.2.5 and I got an issue on Android 4.4.x : when I open Message Center, the loading circle spins indefinitely. And I reopen it some times more, I'm able to open it.
After my debug, I see that happens inside the Fragment and activity of UA library. I think we couldn't fix it cause it's in your library.

**Comment by madelgi** [comment] 2017-05-30 20:08
@toanvc Do you have a weak network connection? I am unable to reproduce this issue, but the behavior you are describing could be the result of a weak connection. If that's not the problem, are there any relevant logs you can attach?

**Comment by toanvc** [comment] 2017-05-30 20:47
@madelgi : I was using a good connection, and I also debugged via Charles, all requests got results after a few ms. Because this is our private app, so I'm unable to send you the logs 😢 
The steps are:
- Open my app
- Open Message Center list
- Open a message => sometimes I get success, but 80% I get loading progress indefinitely

**Comment by madelgi** [comment] 2017-05-30 22:12
@toanvc I can think of two possible causes:

* Charles proxy may be interfering with the connection.
* Is the message expired? Attempting to load a message after it has expired will result in an endless loading screen.

If you're still having trouble, I'd encourage you to get in touch with support for further assistance. This is not reproducible on our end, so I'm going to close it out.

**Closed by madelgi** 2017-05-30 22:12 UTC
