### ISSUE TITLE
com.urbanairship.remotedata.RemoteDataStore.generatePayloadEntries

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#140] opened 2020-02-19 13:11 UTC
Hello,

We have identified crash in `com.urbanairship.remotedata.RemoteDataStore.generatePayloadEntries
` that has affected our users.

![Captura de Tela 2020-02-19 às 10 09 51](https://user-images.githubusercontent.com/5872045/74837353-12e00c80-5300-11ea-877e-264f70eb5a42.png)

![Captura de Tela 2020-02-19 às 10 10 08](https://user-images.githubusercontent.com/5872045/74837359-14a9d000-5300-11ea-9597-22fb3a1de9ea.png)

![Captura de Tela 2020-02-19 às 10 10 22](https://user-images.githubusercontent.com/5872045/74837361-15426680-5300-11ea-8bba-32d88bb2c812.png)

`Fatal Exception: android.database.CursorWindowAllocationException
Cursor window allocation of 2048 kb failed.
android.database.CursorWindow.<init> (CursorWindow.java:108)
android.database.AbstractCursor.moveToFirst (AbstractCursor.java:258)
com.urbanairship.remotedata.RemoteDataStore.generatePayloadEntries (RemoteDataStore.java:208)
com.urbanairship.remotedata.RemoteDataStore.getPayloads (RemoteDataStore.java:178)
com.urbanairship.remotedata.RemoteData$7.apply (RemoteData.java:387)
com.urbanairship.remotedata.RemoteData$7.apply (RemoteData.java:383)
com.urbanairship.reactive.Observable$15.apply (Observable.java:487)
com.urbanairship.reactive.Observable$15.apply (Observable.java:483)
com.urbanairship.reactive.Observable.subscribe (Observable.java:156)
com.urbanairship.reactive.Observable$14.apply (Observable.java:446)
com.urbanairship.reactive.Observable$14.apply (Observable.java:442)
com.urbanairship.reactive.Observable.subscribe (Observable.java:156)
com.urbanairship.reactive.Observable$17.apply (Observable.java:637)
com.urbanairship.reactive.Observable$17.apply (Observable.java:621)
com.urbanairship.reactive.Observable.subscribe (Observable.java:156)
com.urbanairship.reactive.Observable$17.apply (Observable.java:637)
com.urbanairship.reactive.Observable$17.apply (Observable.java:621)
com.urbanairship.reactive.Observable.subscribe (Observable.java:156)
com.urbanairship.reactive.Observable$17.apply (Observable.java:637)
com.urbanairship.reactive.Observable$17.apply (Observable.java:621)
com.urbanairship.reactive.Observable.subscribe (Observable.java:156)
com.urbanairship.remoteconfig.RemoteConfigManager.init (RemoteConfigManager.java:73)
com.urbanairship.UAirship.init (UAirship.java:748)
com.urbanairship.UAirship.executeTakeOff (UAirship.java:409)
com.urbanairship.UAirship.access$000 (UAirship.java:61)
com.urbanairship.UAirship$2.run (UAirship.java:368)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
com.urbanairship.util.AirshipThreadFactory$1.run (AirshipThreadFactory.java:49)
java.lang.Thread.run (Thread.java:761)`

**Comment by BrianBatchelder** [comment] 2020-02-19 21:46
Duplicate of #139.

**Closed by BrianBatchelder** 2020-02-19 21:46 UTC
